### ISSUE TITLE
Investigate networking

### ISSUE THREAD

**Issue by FredTheDino** [FredTheDino/PuckNet#1]

**Comment by sornas** [comment]
https://doc.rust-lang.org/std/net/struct.TcpStream.html

**Comment by sornas** [comment]
Network thread and channels. Library functions that

- gets the latest game state from the network (client),
- sends the new game state to all clients (server)

etc.

**Comment by sornas** [comment]
Threading ensures that we don't block if a state is late. Sometimes we'll skip a state, and sometimes we use the same state two frames in a row. And that's Ok. (Hopefully)

**Comment by sornas** [comment]
In the worst-case we use and send our own inputs _and_ apply received state retro-actively a la rubber banding. Hopefully that won't be needed.

**Comment by sornas** [comment]
WIP on https://github.com/FredTheDino/PuckNet/tree/networking.
