### ISSUE TITLE
fishing mini game

### ISSUE THREAD

**Issue by sornas** [FredTheDino/PuckNet#62]

**Comment by th3tard1sparadox** [comment]
Notify me if this is going to be finished in time so I have time to make the assets for it.

**Comment by FredTheDino** [comment]
Don't think this is gonna be done

**Comment by EMattfolk** [comment]
I think it is pretty easy. We just need a sprite where the player is fishing. The hole in the ice can be part of the sprite, and then we just press a button to start fishing. Notthing will happen of course, but that is expected when fishing in a hockey rink.

**Comment by th3tard1sparadox** [comment]
I'll be able to have four sprites ready by tonight probably. (2-image animation of each color sideway)

**Comment by sornas** [comment]
I think we can get away with only one direction.

**Comment by th3tard1sparadox** [comment]
I thought so too, that is why I said 4 instead of 12 sprites

**Comment by sornas** [comment]
I see. I misunderstood
